  
version: '3'
services:
  mongodb:
    container_name: Mongodb
    image: 'chelepa/mongodb'
    ports:
      - "27017:27017"
    networks:
      - app-tier
  rabbitmq:
    container_name: Rabbitmq
    image: 'chelepa/rabbitmq'
    expose:
     - "5672"
    ports:
     - "15672:15672"
     - "5672:5672"
    networks:
      - app-tier
  redis:
    container_name: redis
    image: 'chelepa/redis'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-tier
    ports:
     - "6379:6379"
      
networks:
  app-tier:
    driver: bridge