version: '3.1'

services:
  db:
    container_name: mysqldb
    image: 'chelepa/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    networks:
      - employee-mysql

networks:
  employee-mysql:
    driver: bridge